# Site settings
title: Christine P'ng | Information Design + Biomedical Communication
email: christine.png@mail.utoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  Information Design + Biomedical Communication
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: _christinepng
github_username:  github_username

# Build settings
markdown: kramdown
plugins_dir: 
  - jekyll-seo-tag

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

gems: [jekyll-paginate]